### ISSUE TITLE
Playlists are not working

### ISSUE THREAD

**Issue by dtop129** [ftk/mpv-confluence#3]
Whenever I try opening a magnet containing multiple files, I get the following

```
[ffmpeg] http: HTTP error 404 Not Found
Failed to open http://localhost:8080/data/infohash/$hash/$filename.
```

I think the problem is with confluence because i could fix this by changing 
`local url = opts.server .. "/data/infohash/" .. infohash .. "/" .. fileinfo.fullpath`
to
`local url = opts.server .. "/data?ih=" .. infohash .. "&path=" .. fileinfo.fullpath`

**Comment by ftk** [comment]
Are you using the latest version? Path-based URLs work only after this commit https://github.com/anacrolix/confluence/commit/17e0dd841a60684201e0e23863b43680ece5d935

**Comment by dtop129** [comment]
Yes I just installed confluence and cloned the repo to mpv.
I noticed that in general the more clean url /data/infohash/../.. doesn't work, so it could be some change in confluence

**Comment by dtop129** [comment]
Actually never mind me the confluence I had installed was the latest github release and not master
